apiVersion: v2
name: kvcache
description: KV Cache — enterprise-grade vendor-neutral KV cache data layer.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/alluxio/kvcache
sources:
  - https://github.com/alluxio/kvcache
keywords:
  - llm
  - inference
  - kv-cache
  - alluxio
  - multi-tenant
maintainers:
  - name: Stephen Pu
    email: stephen.pu@alluxio.com
icon: https://alluxio.io/wp-content/uploads/2022/02/alluxio-logo.png
